In [2]:
# numpyの読み込み
import numpy as np

# AとBの行列を格納する多次元配列のコードを記述する
A = np.array([
    [0, 1],
    [2, 3],
    [4, 5]
])

B = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7]
])

print(A)
print(B)


[[0 1]
 [2 3]
 [4 5]]
[[0 1 2 3]
 [4 5 6 7]]


In [6]:
# AとBの積算
C_at = A @ B

print("行列 A B の積 (C_at):")
print(C_at)

行列 A B の積 (C_at):
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


In [9]:
# 行列 C の要素全体の最大値を求める
max_value = np.max(C_at)

print(f"行列 C_at の最大値: {max_value}")

行列 C_at の最大値: 47
